package cucumberOptions;

import io.cucumber.testng.AbstractTestNGCucumberTests;
import io.cucumber.testng.CucumberOptions;
import org.testng.annotations.DataProvider;

/**
 * FailedTestRunner is a dedicated TestNG runner for re-executing failed Cucumber scenarios.
 * It uses the rerun file (target/failed_scenarios.txt) generated by the main test run
 * to execute only the scenarios that failed previously.
 * This runner helps in isolating and debugging failed tests without re-running the entire suite.
 */
@CucumberOptions(features = "@target/failed_scenarios.txt", // Reads failed scenarios from the rerun file
        glue = "stepDefinitions",                  // Package containing step definition classes
        monochrome = true,                         // Makes console output more readable
        plugin = {"html:target/cucumber.html",        // Generates HTML report
                "json:target/cucumber.json",        // Generates JSON report
                "com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:" // Extent report adapter
        })
public class FailedTestRunner extends AbstractTestNGCucumberTests {

    /**
     * Overrides the default scenarios() method to enable parallel execution of failed scenarios.
     * This allows faster re-execution of failed tests for quicker debugging.
     *
     * @return two-dimensional array of failed scenarios for parallel execution
     */
    @Override
    @DataProvider(parallel = true)
    public Object[][] scenarios() {
        return super.scenarios();
    }
}
